"use client";
import { useEffect,useMemo,useState } from "react";
const STATUSES=["Chat Builder","Tanya Aja","Qualified","Quotation Dikirim","Hot","Closing","Tidak Layak"];
type Lead={id:string;wa_id:string;phone:string|null;name:string|null;status:string;source:string;source_id:string|null;ad_headline:string|null;last_message:string|null;last_seen_at:string;revenue:number|string};
const rupiah=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v||0);
const dateTime=(v:string)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(new Date(v));
export default function Dashboard(){
 const [leads,setLeads]=useState<Lead[]>([]),[drafts,setDrafts]=useState<Record<string,{status:string;revenue:string}>>({}),[loading,setLoading]=useState(true),[savingId,setSavingId]=useState<string|null>(null),[error,setError]=useState(""),[q,setQ]=useState(""),[statusFilter,setStatusFilter]=useState(""),[sourceFilter,setSourceFilter]=useState("");
 async function load(){setLoading(true);setError("");try{const p=new URLSearchParams();if(statusFilter)p.set("status",statusFilter);if(sourceFilter)p.set("source",sourceFilter);if(q.trim())p.set("q",q.trim());const r=await fetch(`/api/leads?${p.toString()}`,{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Gagal mengambil lead");setLeads(j.leads);const d:any={};for(const l of j.leads)d[l.id]={status:l.status,revenue:String(Number(l.revenue||0))};setDrafts(d);}catch(e:any){setError(e.message||"Error");}finally{setLoading(false);}}
 useEffect(()=>{load();},[statusFilter,sourceFilter]); useEffect(()=>{const t=setTimeout(()=>load(),350);return()=>clearTimeout(t);},[q]);
 async function saveLead(lead:Lead){const d=drafts[lead.id];if(!d)return;setSavingId(lead.id);try{const r=await fetch(`/api/leads/${lead.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:d.status,revenue:Number(d.revenue||0)})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Gagal simpan");await load();}catch(e:any){setError(e.message||"Gagal simpan");}finally{setSavingId(null);}}
 const summary=useMemo(()=>{const highIntent=leads.filter(l=>["Qualified","Quotation Dikirim","Hot","Closing"].includes(l.status)).length,closing=leads.filter(l=>l.status==="Closing").length,revenue=leads.filter(l=>l.status==="Closing").reduce((s,l)=>s+Number(l.revenue||0),0);return{total:leads.length,highIntent,closing,revenue};},[leads]);
 const counts=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s,leads.filter(l=>l.status===s).length])),[leads]);
 return <main className="shell"><div className="header"><div><h1>Gudang WPC CRM</h1><p>Tracking WhatsApp → qualified → quotation → closing.</p></div><button className="refresh" onClick={load}>Refresh</button></div>{error&&<div className="error">{error}</div>}<section className="cards"><div className="card"><div className="label">Total lead</div><div className="value">{summary.total}</div></div><div className="card"><div className="label">High Intent</div><div className="value">{summary.highIntent}</div></div><div className="card"><div className="label">Closing</div><div className="value">{summary.closing}</div></div><div className="card"><div className="label">Revenue Closing</div><div className="value">{rupiah(summary.revenue)}</div></div></section><div className="funnel">{STATUSES.map(s=><span className="pill" key={s}>{s}<b>{counts[s]??0}</b></span>)}</div><section className="toolbar"><input className="control" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, nomor WA, pesan…"/><select className="control" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Semua status</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select className="control" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">Semua sumber</option><option>Meta Ads</option><option>WhatsApp Organic</option></select></section><section className="panel"><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Sumber</th><th>Pesan terakhir</th><th>Waktu</th><th>Status</th><th>Revenue</th><th></th></tr></thead><tbody>{!loading&&leads.map(lead=>{const d=drafts[lead.id]??{status:lead.status,revenue:String(Number(lead.revenue||0))};return <tr key={lead.id}><td><div className="name">{lead.name||"Tanpa nama"}</div><div className="sub">{lead.phone||`+${lead.wa_id}`}</div></td><td><div className={lead.source==="Meta Ads"?"source-meta":""}>{lead.source}</div>{lead.source_id&&<div className="sub">Ad ID: {lead.source_id}</div>}{lead.ad_headline&&<div className="sub">{lead.ad_headline}</div>}</td><td><div className="message">{lead.last_message||"—"}</div></td><td>{dateTime(lead.last_seen_at)}</td><td><select className="status-select" value={d.status} onChange={e=>setDrafts(x=>({...x,[lead.id]:{...d,status:e.target.value}}))}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></td><td><input className="revenue" inputMode="numeric" value={d.revenue} onChange={e=>setDrafts(x=>({...x,[lead.id]:{...d,revenue:e.target.value.replace(/[^\d]/g,"")}}))}/></td><td><button className="save" disabled={savingId===lead.id} onClick={()=>saveLead(lead)}>{savingId===lead.id?"Simpan…":"Simpan"}</button></td></tr>})}</tbody></table></div>{!loading&&leads.length===0&&<div className="empty">Belum ada lead.</div>}{loading&&<div className="empty">Memuat lead…</div>}</section></main>;
}
